# -*- coding: utf-8 -*-
"""tweepy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvmSvwXC-jKntRHUYMm5LVgQXqg09gBS

# **Código de Tweepy para extraer datos de twitter**
"""

import pandas as pd
import tweepy as twpy
from tweepy import OAuthHandler

"""## **1. Permiso para usar la API**

*Códigos de acceso*
"""

access_token = '####'
access_token_secret = '####'
api_key = '####'
api_secret_key = '####'

autorizacion = twpy.OAuthHandler(api_key, api_secret_key)
autorizacion.set_access_token(access_token, access_token_secret)

"""## **2. Set up de la API**"""

api = twpy.API(autorizacion, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

tweets = []
account = "@user"

"""## **3. Extracción de los datos**"""

# Para tweets desde cierta fecha:
# for tweet in twpy.Cursor(api.search, q=account, since='2019-12-31').items():
#
# Para tweets hasta cierta fecha:
# for tweet in twpy.Cursor(api.search, q=account, max_id='2019-12-31').items():
#
# Para un numero exacto de tweets:
# for tweet in twpy.Cursor(api.search, q=account).items(50000):

for tweet in twpy.Cursor(api.search, q=account).items():
  
	try: 
		data = [tweet.created_at, tweet.id, tweet.text, tweet.user._json['screen_name'], tweet.user._json['name'], tweet.user._json['created_at'], tweet.entities['urls']]
		data = tuple(data)
		tweets.append(data)

	except twpy.TweepError as e:
		print(e.reason)
		continue

	except StopIteration:
		break

"""## **4. Set up de los datos para su análisis**"""

tweets_df = pd.DataFrame(tweets, columns = ['created_at','tweet_id', 'tweet_text', 'screen_name', 'name', 'account_creation_date', 'urls'])

# Guardar datos en un csv
# tweets_df.to_csv(path_or_buf = '/twitterData.csv', index=False)